### ISSUE TITLE
Unable to move using Shift

### ISSUE THREAD

**Issue by Mulch213** [dekuScrub731/picture-in-picture#10]
Hello, I am unable to to move the PIP using shift. I am not sure what could be causing this, maybe it isn't in the actual client yet.

**Comment by dekuScrub731** [comment]
Hey, you are correct, that functionality hasn't made it to the plugin hub just yet (I got ahead of myself with updating the readme). I'm figuring out the best way to store the configuration before moving forward.

**Comment by dekuScrub731** [comment]
Released with v1.4
