### ISSUE TITLE
Clicking picture in picture opens up the NVIDIA performance tab

### ISSUE THREAD

**Issue by cmsu224** [dekuScrub731/picture-in-picture#3]
When clicking the small picture-in-picture preview, it also opens up the NVDIA performance tab as well as runelite: 
![image](https://user-images.githubusercontent.com/14130954/126635252-5f99028c-8c8e-4043-9f82-14f899e50a7b.png)

**Comment by dekuScrub731** [comment]
A new version 1.1.1 is now in the plugin hub, which uses RuneLite's **request** focus method (instead of **force** focus). Can you see if that resolves the issue (might need to relaunch RL for it to pull the latest plugin).

**Comment by cmsu224** [comment]
Yes, the issue has been fixed.  Thanks!
