### ISSUE TITLE
Better downscaling quality

### ISSUE THREAD

**Issue by orlp** [dekuScrub731/picture-in-picture#4]
I see that right now you use `Image.SCALE_FAST` to create the PIP. Maybe add an option to use `Image.SCALE_SMOOTH`
for better quality?

**Comment by dekuScrub731** [comment]
Version 1.2 adds options for the render quality of the picture in picture. The plugin couldn't handle `Image.SCALE_SMOOTH`, so I reworked the plugin to use `Graphics2D` over the `getScaledInstance` method.
- Low = Nearest Neighbor rendering hint
- Medium = Bilinear rendering hint
- High = Bilinear rendering hint (in two passes)

**Comment by orlp** [comment]
@dekuScrub731 I must say I find the two passes as high quality suspect, but I'd have to look at it. I don't know why two downscale passes would improve the quality. Good work either way.

**Comment by dekuScrub731** [comment]
@orlp - The two passes are progressive, similar to what's described here: [https://stackoverflow.com/questions/24745147/java-resize-image-without-losing-quality#36367652](https://stackoverflow.com/questions/24745147/java-resize-image-without-losing-quality#36367652)

I thought the progressive bilinear looked better than a single bicubic. Also played around with progressive bicubic and 3+ passes on bilinear, but started skipping frames at faster refresh rate (I'm running with an APU at the moment). I'll keep playing around with it out of curiosity.
