### ISSUE TITLE
Clicking the window on linux doesn't bring RuneLite to the top

### ISSUE THREAD

**Issue by w0** [dekuScrub731/picture-in-picture#8]
Clicking the pip window on linux gives focus to the application. But RuneLite stays behind all the other running applications. I am currently running pop_os 21.04. Let me know if I can help test anything.

**Comment by dekuScrub731** [comment]
@w0 - Under the "RuneLite" configuration screen, does "Request Focus" bring RL to the top when triggered (idle notification)? Does "Force Focus" work?

The PIP plugin currently calls RL's "Request" option, but I could add a configurable option for "Force" if that's needed for Linux.

**Comment by w0** [comment]
I tried both options and I am still getting the same behavior. Even tried restarting the client after changing the settings The RuneLite notifications don't move the application window to the top after giving focus either. This might be a bug in my desktop environment (GNOME).

**Comment by dekuScrub731** [comment]
Version 1.2 provides configurable options for Click Action, one of which is "Force Focus." It sounds like you already tried triggering this through RuneLite notifications with no success, but maybe give it another try on the Picture in Picture plugin? If that still doesn't work, you may want to enter an issue on the RuneLite repository for better Linux support requesting/forcing focus.
